### ISSUE TITLE
Panic using 'event' command line flag

### ISSUE THREAD

**Issue by scsibug** [fiatjaf/noscl#1]
I'm experiencing a segfault with `noscl` using the `event` option.  Example:

```
~/go/bin/noscl event 5812eab28abadc3216e560f116cc41f98f1bf4124293432cd6d39936e67a63f9
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1273561]

goroutine 1 [running]:
github.com/fiatjaf/go-nostr/relaypool.(*RelayPool).Sub(0x0, 0x7ff7bfeffa0a, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/scsibug/go/pkg/mod/github.com/fiatjaf/go-nostr@v0.1.0/relaypool/relaypool.go:163 +0x1c1
main.view(0xc0000136b0)
	/Users/scsibug/go/pkg/mod/github.com/fiatjaf/noscl@v0.2.0/event.go:13 +0x125
main.main()
	/Users/scsibug/go/pkg/mod/github.com/fiatjaf/noscl@v0.2.0/main.go:87 +0x708
```

**Comment by fiatjaf** [comment]
Sorry, noscl was never properly tested (or finished). Will look into this in the next few days.

**Comment by fiatjaf** [comment]
Fixed.
