### ISSUE TITLE
Panic on metadata update

### ISSUE THREAD

**Issue by scsibug** [fiatjaf/noscl#2]
Got a panic on the latest release while updating metadata.  Event publishing succeeded.
```
noscl metadata --name=bestofhn --description="The Best of Hacker News"  --image="https://news.ycombinator.com/y18.gif"
Sent event 2dd9b62dbca442b5dd2fb8243ab7273117f6ba43d4cdcb213007e8e372453c48 to 'wss://relayer.fiatjaf.com'.
Sent event 2dd9b62dbca442b5dd2fb8243ab7273117f6ba43d4cdcb213007e8e372453c48 to 'wss://nostr-pub.wellorder.net'.
panic: concurrent write to websocket connection

goroutine 13 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0003ec060, 0x101, 0x0, 0x0, 0x0, 0x2240108, 0x30)
	/Users/scsibug/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:610 +0x62e
github.com/gorilla/websocket.(*messageWriter).Close(0xc0003ec060, 0x0, 0xc00033d948)
	/Users/scsibug/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:724 +0x65
github.com/gorilla/websocket.(*Conn).beginMessage(0xc00019a9a0, 0xc000140e40, 0x1, 0xc00033d998, 0x1081b7c)
	/Users/scsibug/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:473 +0x262
github.com/gorilla/websocket.(*Conn).NextWriter(0xc00019a9a0, 0x1, 0x18, 0x12b9900, 0xc00033da88, 0x1208e18)
	/Users/scsibug/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:513 +0x53
github.com/gorilla/websocket.(*Conn).WriteJSON(0xc00019a9a0, 0x12ae2c0, 0xc000148f48, 0xc000148f48, 0xc0003a5cb8)
	/Users/scsibug/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/json.go:24 +0x49
github.com/fiatjaf/go-nostr/relaypool.Subscription.Sub(0xc0003a5cd0, 0xe, 0xc000140e10, 0x0, 0x0, 0x0, 0xc000144540, 0x0, 0xc0001445a0, 0xc00033de78, ...)
	/Users/scsibug/go/pkg/mod/github.com/fiatjaf/go-nostr@v0.2.0/relaypool/subscription.go:51 +0x1e9
github.com/fiatjaf/go-nostr/relaypool.(*RelayPool).Sub(0xc00009b9b0, 0xc00033de78, 0x1, 0x1, 0x0)
	/Users/scsibug/go/pkg/mod/github.com/fiatjaf/go-nostr@v0.2.0/relaypool/relaypool.go:181 +0x405
github.com/fiatjaf/go-nostr/relaypool.(*RelayPool).PublishEvent.func1(0xc000544930, 0xc000408660, 0xc00009b9b0, 0xc000208d20, 0x19, 0xc0000e2160)
	/Users/scsibug/go/pkg/mod/github.com/fiatjaf/go-nostr@v0.2.0/relaypool/relaypool.go:216 +0x1a7
created by github.com/fiatjaf/go-nostr/relaypool.(*RelayPool).PublishEvent
	/Users/scsibug/go/pkg/mod/github.com/fiatjaf/go-nostr@v0.2.0/relaypool/relaypool.go:208 +0x131
```

**Comment by Koshroy** [comment]
Should the relay pool have a mutex around it? Alternatively, the pool can be run in a goroutine that accepts method calls through the channel.

**Comment by fiatjaf** [comment]
I think the mutex approach is simpler, right? Yeah, I guess that's the solution,.
